apiVersion: apps/v1
kind: Deployment
metadata:
  name: crudkub-server
  labels:
    app: crudkub-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crudkub-server
  template:
    metadata:
      labels:
        app: crudkub-server
    spec:
      containers:
      - name: crudkub-server
        image: ${ACR_NAME}/crudkub-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: postgres-secret
