apiVersion: v1
kind: Service
metadata:
  name: crudkub-server
spec:
  selector:
    app: crudkub-server
  type: LoadBalancer  # Use ClusterIP for internal, LoadBalancer for external
  ports:
  - protocol: TCP
    port: 3000          # External port
    targetPort: 3000  # Container port (must match deployment)